### ISSUE TITLE
Supporting additional data for subscriptions

### ISSUE THREAD

**Issue by roguedarkjedi** [sharkbound/PythonTwitchBotFramework#11]
I don't have support for this yet but it would be kinda nice to see the other data for subscriptions to be implemented. 

Like:

`msg-param-cumulative-months` and `msg-param-months`

msg-param-sub-plan (this one's weird because it's numbers unless its `Prime`, so maybe just explicitly check value and if `Prime` set to 0)

**Comment by sharkbound** [comment]
merged
