### ISSUE TITLE
Sugestion: Support for various database backends

### ISSUE THREAD

**Issue by JustDevZero** [sharkbound/PythonTwitchBotFramework#29]
As I see the project uses sqlalchemy, I think makes no sense to just support mysql. It could be clever to not make a database locking.

**Comment by JustDevZero** [comment]
As promised @sharkbound doing the changes was really easy, as you don't use any mysql specific stuff.

A Pull Request has been created:

https://github.com/sharkbound/PythonTwitchBotFramework/pull/30

**Comment by sharkbound** [comment]
thanks, i will probably hand-pick the needed changes when i get to doing this, since there is a lot of minor formatting changes included in the PR.
but i will be sure to credit you

**Comment by sharkbound** [comment]
i am closing this issue, keeping discussion on this in the comments for the PR

**Comment by sharkbound** [comment]
FYI, i am working on implementing this, i currently planning how to do it atm, as i am not sure that connection strings will all use the same format

**Comment by JustDevZero** [comment]
On the link I provided before you can check for the connection strings.
But the TLDR is:
Yes, they have all the same format  but SQLITE which is a bit different.

**Comment by sharkbound** [comment]
i will be pushing a update to add multi-db support soonish, hopefully tonight

**Comment by sharkbound** [comment]
added in commit 863eb6585b3df865f7a62254f529398957e6e848
