### ISSUE TITLE
kraken api defunct

### ISSUE THREAD

**Issue by Wallboy** [sharkbound/PythonTwitchBotFramework#43]
Hi,

Not sure if this project is still being maintained, but the kraken API has been decommissioned a few months ago so "get_user_creation_date" will no longer work.

**Comment by sharkbound** [comment]
it is still maintained, and i will be removed that function, i already went through the bot and checked that it was not using kracken for anything else other than that

**Comment by sharkbound** [comment]
removed `get_user_creation_date` in commit 1f164704a2a543dbae9aef641740bc3bf3aa1137
