### ISSUE TITLE
!duel game broken

### ISSUE THREAD

**Issue by Wallboy** [sharkbound/PythonTwitchBotFramework#46]
The !duel game is quite broken. 

**1)** First off, there is no balance checking at all, so you can duel somebody with any currency amount: `!duel someone 9999999`

**2)** Secondly, the winner doesn't seem to actually get the currency winnings at all. Running `!bal` after winning results in the same amount you had prior to the duel.

**Solution:** The issue is with the logic in Line 402 in currency_commands.py: `loser = msg.author if winner == msg.author else challenger` results in setting both the winner and loser to the same person. The line should instead be `loser = msg.author if winner != msg.author else challenger`

**Comment by sharkbound** [comment]
fixed in commit 4b201eb0f5941852748313d4ef8eb5c3b70346ab  and pushed in pypi version `2.4.2`
