### ISSUE TITLE
Class PubSubBits missing from __init__.py

### ISSUE THREAD

**Issue by polysyllabic** [sharkbound/PythonTwitchBotFramework#50]
To import this class, I currently need to use 

    from twitchbot.pubsub.bits_model import PubSubBits

PubSubBits should be in the __init__.py file so it can be imported with

    from twitchbot import PubSubBits

**Comment by sharkbound** [comment]
i will fix this now, thanks for spotting this!

**Comment by sharkbound** [comment]
fixed in version 2.4.6
