### ISSUE TITLE
Whisper reply not working

### ISSUE THREAD

**Issue by SellA** [sharkbound/PythonTwitchBotFramework#6]
I'm not able to get the bot reply to whisper. Message type is WHISPER and the bot act as it has replied via whisper, but nothing appears on the private chat on twitch. Am I missing something?

**Comment by sharkbound** [comment]
tested it out with this code:
```python
@Command('whisper', context=CommandContext.WHISPER)
async def cmd_whisper(msg: Message, *args):
    await msg.reply('got it!')
```

and it seems to work fine with that testing command:
![image](https://user-images.githubusercontent.com/12285026/63196764-b2fc6680-c03b-11e9-9898-5b2021afdb61.png)

**Comment by SellA** [comment]
I tried with your snippet and i get the same behaviour as my tests. This is the log output when i send a whisper:
```
michelesella -> halbot9000: !whisper
halbot9000 -> michelesella: got it!
```
I've also updated the bot from github (i've installed it with pip).

It seems to be working correctly for what i see in logs and behaviour, but the whisper don't show up on twitch. Maybe is there some setting that i've forgot to turn on on twitch?

**Comment by sharkbound** [comment]
this is probably not the case, but have you verified the oauth is correct?

**Comment by sharkbound** [comment]
closing this for now, leave a reply if it is still happening

**Comment by Scurge** [comment]
I'm having this same issue. on version 1.15.7, python 3.7.3.
I see the whisper in the console output but it is never received by the user.  The commands that do not whisper show up fine in the chat.  I'm pretty confident the oauth is correct, it works using the twichIO framework and if I change a single character, it wont log on.

**Comment by sharkbound** [comment]
seems related to not-known bots, or new bot accounts
https://dev.twitch.tv/docs/irc/guide/#known-and-verified-bots

closing until i find more info out
